    "9 fingers on each appendage.",
    "A culture of planners.",
    "A reptilian species obsessed with battle.",  
    "A winged humanoid species sometimes capable of flight.", 
    "Abusive to their gear.",
    "Addicted to rubbing energy cells in it's audio canals.",
    "Adopts other cultures' traditions over it's own.",
    "Allergic to Bananas.",  
    "Always travels in groups.",
    "Amphibious with a great sense of 3d space.",
    "Anarchist culture.",
    "Artist culture.",
    "Asexual.",
    "Athletic culture.",
    "Attracted to Dad bods.",
    "Barbarian culture.",
    "Bards by tradition.",
    "Believes in ghosts.",
    "Believes space is flat.",
    "Blind culture.",
    "Blue.",
    "Body modified to prefer and be healthiest on synthetic foods.",
    "Brown stripes sometimes across, sometimes down.",
    "Cake eater.",
    "Can see a broader spectrum of light.",
    "Can sleep in trees.",
    "Cannibalistic but under control.",
    "Cannot lie.",
    "Carnivorous.",
    "Carries towels everywhere.",
    "Changes names frequently.",
    "Chokes on non-liquid food.",
    "Clostrophobic in spacesuits"
    "Clumsy in low gravity.",
    "Collects shiny objects.",
    "Compulsive documenter.",
    "Constantly celebrates holidays.",
    "Constantly counts things.",
    "Cries once a day.  Tears provide nutrients.",
    "Culture of gambling and chance.",
    "Culture of tattooing and body modification.",
    "Dances when nervous.",
    "Deaf culture.",
    "Death rituals for any being's death.",
    "Descended from magicians.",
    "Descended from slaves.",
    "Does not age at the same rate when asleep.",
    "Does not believe in remembering names.",
    "Does not believe in wearing clothes over their torso.",
    "Does not sleep.  Meditates.",
    "Does not wear clothes.",
    "Does not wear shoes.",
    "Doesn't understand sarcasm.",
    "Drinks it's urine.",
    "Eats metal.",
    "Eats once a week.",
    "Eats through skin pores on face.",
    "Echolocation instead of sight.",
    "Egg-shaped head.",
    "Elaborate hairstyles.",
    "Elaborate self-care regimen.",
    "Emotional need to lie, but skin changes color when doing so.",
    "Emotionally attached to machines.",
    "Essentially drunk or high all the time.",
    "Ettiquette obsessed.",
    "Everyone has beards.",
    "Expects to modify it's clothes frequently.",
    "External Jaw.",
    "Extreme personal space requirements.",
    "Flat head.",
    "Fluffy fashion.",
    "Folds into a ball to rest.",
    "Food is inedible to most other species.",
    "From a flat world. Often afraid of heights.",
    "Frowns when happy.",
    "Furry Face.",
    "Gangly.",
    "Gender changes periodically.",
    "Genderless.",
    "Generally bad sense of hearing, but skin can be exposed to naked space.",
    "Given to narcolepsy.",
    "Glowing collarbone.",
    "Goes to the bathroom a lot.",
    "Gray bumps on forearms.",
    "Green skin.", 
    "Green.",
    "Hair stands up when feeling danger.",
    "Hairy appendages.",
    "Hallucinates when dehydrated.",
    "Has a beak.",
    "Has a hump.",
    "Has a prehensile tongue.",
    "Has a shell.",
    "Has a small snout nose.",
    "Has a tail.",
    "Has a third eye.",
    "Has a third, sometimes usable arm.",
    "Has antennae.",
    "Has bioluminescent markings.",
    "Has fur.",
    "Has gills.",
    "Has pets or symbiotes.",
    "Has pets.",
    "Has scales.",
    "Has seven hearts.",
    "Head blows up like a balloon and can hold breath for 30 minutes.",
    "Hibernates in certain gravitational conditions.",
    "Hoarder.",
    "Hot beverages required.",
    "Howls at mooons.",
    "Hums constantly.",
    "Hydrates compulsively.",
    "Interjects humor in all situations.",
    "Jet Black Skin.",
    "Known to hover.",
    "Laughs like a flute.",
    "Licks its body for cleanliness.",
    "Licks its body for vitamin intake.",
    "Life force can be added to new body upon ritual death.",
    "Like a mom.", 
    "Literalist.",
    "Loses inhibitions when dehydrated.",
    "Luck worshipers.",
    "Math is useless.",
    "Medium sized.",
    "Microbiome culture in each individual with democratic control.",
    "Moment of silence every hour on the hour.",
    "Muscular.",
    "Mute culture.",
    "Naturally magnetic body.",
    "Never nude.",
    "No sense of smell.",
    "Obsesed with star charts.",
    "Obsessed with cleanliness.",
    "Obsessed with glass technology.",
    "Obsessed with lineage.",
    "Obsessed with sentence structure.",
    "Obsessed with socks.",
    "Often wet.",
    "Only wears clothes when swimming.",
    "Orcish features.",
    "Overexplains everything.",
    "Owned by corporation.",
    "Pacifists.",
    "Prefers high gravity environments.",
    "Prefers low gravity environments.",
    "Prefers rocky terrain to indoor spaces.",
    "Prefers the company of home system species.",
    "Prefers underground spaces.",
    "Rarely bathes.",
    "Reads by sensory touch.",
    "Removable limbs under certain conditions.",
    "Reproduces frequently.  Children mature in a short cycle.",
    "Rolls.",
    "Rotund.",
    "Sees auras.",
    "Sees in infrared, not in visible spectrum.",
    "Self-mutilation rituals.",
    "Sensory overloaded easily.  Wears noise-cancelling headphones and dark glasses.",
    "Sensual.",
    "Shades of bright pink everywhere.",
    "Sheds seeds that can be grown as food.",
    "Short.",
    "Showers sometimes 12 times a day.",
    "Slender.",
    "Smells like cinnamon.",
    "Smells like lavender.",
    "Smells like sulfur.",
    "Smiles.",
    "Smokes a variety of substances.",
    "Sniffs everything.",
    "Snores while awake.",
    "Society of tightrope walkers.",
    "Solar dependent.",
    "Sometimes sees dead people.",
    "Space coffee addict.",
    "Space Dwarf.",
    "Space Elf.",
    "Speaks in gibberish constantly.",
    "Speaks in rhymes.",
    "Speaks primarily through historical reference and metaphor.",
    "Spiky fashion.",
    "Spiritually connected to weapoons or gear.",
    "Stocky feet.",
    "Stomps when walks.",
    "Struggles in space.",
    "Susceptible to forms of mind control.",
    "Sweats glitter.",
    "Symmetrical obsession.",
    "Synthetic body parts.",
    "Tall.",
    "Teeth regrow.",
    "The worst rules lawyer ever.",
    "Turns color when body senses death.",
    "Twitchy.",
    "Two fingers per hand.  Speaks binary in clicks and whistles.",
    "Uncontrollable remote viewing ability.",
    "Very tall.",
    "Wears a collar.",
    "Wears clothes just on its torso.",
    "Wears gloves all the time.",
    "Wears hats.",
    "Wears just pants.",
    "Wears sandals all the time.",
    "Wears shorts in cold weather.",
    "Wide bodied.",
    "Yard gnome."